blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussions
    url: https://github.com/asayed18/awsf/discussions
    about: Ask questions and discuss ideas with the community
  - name: ğŸ“š Documentation
    url: https://github.com/asayed18/awsf#readme
    about: Check out the documentation and guides
